import { imagekit } from "@/lib/imagekit";
import prisma from "@/lib/prisma";
import fs from "fs";
import path from "path";

const recipes = [
  {
    name: "Jollof Rice",
    ingredients: [
      "4 cups long-grain parboiled rice",
      "2 red bell peppers",
      "4 tomatoes",
      "2 onions",
      "1/4 cup vegetable oil",
      "2 tbsp tomato paste",
      "2 cups chicken stock",
      "2 tsp curry powder",
      "2 tsp thyme",
      "Salt and seasoning cubes to taste",
    ],
    description:
      "A smoky, spicy, and tomato-rich rice dish, often cooked for parties and gatherings, loved across West Africa",
    instructions: [
      "Blend peppers, tomatoes, and 1 onion.",
      "Heat oil, sauté onions, and add tomato paste.",
      "Add blended mix, spices, and cook until reduced.",
      "Stir in stock, rice, and seasonings.",
      "Cover and cook on low heat until rice is done.",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    servings: 6,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 350,
    tags: ["rice", "party", "stew"],
    image: "public/uploads/jellof.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Egusi Soup",
    description:
      "A hearty melon seed soup thickened with ground egusi, cooked with meats and vegetables, perfect with pounded yam or fufu.",
    ingredients: [
      "2 cups ground egusi seeds",
      "1/2 cup palm oil",
      "500g beef",
      "200g stockfish",
      "200g spinach or bitterleaf",
      "2 tbsp crayfish",
      "2 scotch bonnet peppers",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Boil beef and stockfish with seasoning.",
      "Heat palm oil, fry blended pepper and crayfish.",
      "Add ground egusi paste and stir.",
      "Pour in stock, add meat, and simmer.",
      "Stir in vegetables and cook for 5 minutes.",
    ],
    prepTimeMinutes: 25,
    cookTimeMinutes: 45,
    servings: 5,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 400,
    tags: ["soup", "traditional", "swallow"],
    image: "public/uploads/egusi.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Efo Riro",
    description:
      "A rich Yoruba-style spinach stew simmered with peppers, meats, and palm oil, bursting with flavor.",
    ingredients: [
      "500g spinach leaves",
      "1/2 cup palm oil",
      "500g goat meat",
      "200g stockfish",
      "2 scotch bonnet peppers",
      "2 onions",
      "2 tbsp crayfish",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Cook goat meat and stockfish with seasoning.",
      "Blend peppers and onions.",
      "Heat palm oil, fry pepper mix.",
      "Add crayfish, meat, and stock.",
      "Add spinach and cook for 5 minutes.",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 320,
    tags: ["soup", "vegetable", "swallow"],
    image: "public/uploads/efo-riro.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Suya",
    description:
      "Spicy, peanut-coated grilled beef skewers, Nigeria’s most iconic street food, usually served with onions and pepper mix.",
    ingredients: [
      "500g beef",
      "2 tbsp ground peanuts",
      "2 tsp cayenne pepper",
      "1 tsp paprika",
      "1 tsp ginger powder",
      "Salt",
      "Vegetable oil",
    ],
    instructions: [
      "Slice beef thinly.",
      "Mix spices and coat beef.",
      "Thread beef on skewers.",
      "Grill over hot charcoal, basting with oil.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 250,
    tags: ["street food", "grill", "spicy"],
    image: "public/uploads/suya.jpeg",
    mealType: ["snack", "dinner"],
  },
  {
    name: "Moi Moi",
    description:
      "Steamed bean pudding made from blended beans, peppers, and spices, often stuffed with eggs or fish.",
    ingredients: [
      "2 cups peeled beans",
      "1 red bell pepper",
      "1 onion",
      "1 scotch bonnet",
      "1/4 cup vegetable oil",
      "2 boiled eggs",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Blend beans with pepper and onion.",
      "Mix in oil, seasoning, and water.",
      "Pour batter into bowls, add eggs.",
      "Steam for 45 minutes until firm.",
    ],
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 280,
    tags: ["beans", "protein", "healthy"],
    image: "public/uploads/moi.jpeg",
    mealType: ["breakfast", "lunch", "dinner"],
  },
  {
    name: "Akara",
    description:
      "Crispy golden bean fritters, fluffy inside, usually eaten at breakfast with pap (ogi) or bread.",
    ingredients: [
      "2 cups peeled beans",
      "1 onion",
      "2 scotch bonnet peppers",
      "Salt",
      "Vegetable oil",
    ],
    instructions: [
      "Blend beans with onion and pepper.",
      "Season with salt.",
      "Scoop batter into hot oil.",
      "Fry until golden brown.",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 180,
    tags: ["breakfast", "street food", "beans"],
    image: "public/uploads/akara.jpeg",
    mealType: ["breakfast", "snack"],
  },
  {
    name: "Pepper Soup",
    description:
      "A light, watery broth spiced with unique Nigerian pepper soup spice mix, warming and perfect for rainy days.",
    ingredients: [
      "1kg goat meat or fish",
      "2 tbsp pepper soup spice mix",
      "2 scotch bonnet peppers",
      "2 onions",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Boil meat with onion and seasoning.",
      "Add pepper soup spice and peppers.",
      "Simmer until meat is tender.",
      "Serve hot.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    servings: 5,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 220,
    tags: ["soup", "spicy", "comfort food"],
    image: "public/uploads/pepper-soup.jpeg",
    mealType: ["dinner"],
  },
  {
    name: "Ofada Rice and Ayamase Sauce",
    description:
      "Locally grown rice served with a fiery green pepper stew (ayamase), a delicacy for special occasions.",
    ingredients: [
      "4 cups ofada rice",
      "6 green bell peppers",
      "2 scotch bonnet peppers",
      "1/2 cup palm oil",
      "500g assorted meats",
      "2 tbsp crayfish",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Cook ofada rice until tender.",
      "Blend peppers and onions.",
      "Bleach palm oil, add pepper mix.",
      "Add meats, crayfish, and seasoning.",
      "Simmer until thick.",
    ],
    prepTimeMinutes: 30,
    cookTimeMinutes: 50,
    servings: 6,
    difficulty: "Hard",
    cuisine: "Nigerian",
    caloriesPerServing: 400,
    tags: ["rice", "traditional", "spicy"],
    image: "public/uploads/ofada-rice.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Okra Soup",
    description:
      "A slimy yet delicious soup made with okra, palm oil, and meats, best paired with fufu or pounded yam.",
    ingredients: [
      "500g okra",
      "1/2 cup palm oil",
      "500g beef",
      "200g stockfish",
      "2 tbsp crayfish",
      "2 scotch bonnet peppers",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Boil beef and stockfish with seasoning.",
      "Blend peppers and crayfish.",
      "Heat palm oil, add pepper mix.",
      "Add okra and simmer briefly.",
      "Stir in meat and serve.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 5,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 300,
    tags: ["soup", "okra", "swallow"],
    image: "public/uploads/okra.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Pounded Yam and Egusi",
    description:
      "Soft, stretchy yam dough served alongside thick, nutty egusi soup, a classic Nigerian comfort meal.",
    ingredients: [
      "6 Medium yams",
      "2 cups ground egusi",
      "1/2 cup palm oil",
      "500g assorted meats",
      "2 scotch bonnet peppers",
      "Spinach leaves",
    ],
    instructions: [
      "Boil yam and pound until smooth.",
      "Prepare egusi soup as usual.",
      "Serve pounded yam with egusi soup.",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    servings: 4,
    difficulty: "Hard",
    cuisine: "Nigerian",
    caloriesPerServing: 500,
    tags: ["swallow", "yam", "soup"],
    image: "public/uploads/egusi-pounded-yam.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Bole (Roasted Plantain)",
    description:
      "Charcoal-roasted ripe plantains with a smoky sweetness, usually eaten with groundnuts or spicy sauce.",
    ingredients: [
      "6 ripe plantains",
      "Groundnut (peanuts) for serving",
      "Palm oil sauce (optional)",
    ],
    instructions: [
      "Peel plantains.",
      "Roast over charcoal grill or in oven until golden brown.",
      "Serve with groundnut or spicy palm oil sauce.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 25,
    servings: 6,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 200,
    tags: ["street food", "plantain", "snack"],
    image: "public/uploads/bole.jpeg",
    mealType: ["snack", "dinner"],
  },
  {
    name: "Nkwobi",
    description:
      "A rich delicacy of cow foot simmered in spicy palm oil sauce, commonly enjoyed as an evening treat.",
    ingredients: [
      "1kg cow foot",
      "1/2 cup palm oil",
      "2 tbsp potash (Akanwu)",
      "2 scotch bonnet peppers",
      "1 onion",
      "Utazi leaves",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Cook cow foot until soft.",
      "Mix palm oil and potash until thick and yellow.",
      "Add pepper, onion, and seasoning.",
      "Stir in meat and garnish with utazi.",
    ],
    prepTimeMinutes: 30,
    cookTimeMinutes: 90,
    servings: 5,
    difficulty: "Hard",
    cuisine: "Nigerian",
    caloriesPerServing: 450,
    tags: ["traditional", "meat", "delicacy"],
    image: "public/uploads/nkwobi.jpeg",
    mealType: ["dinner"],
  },
  {
    name: "Afang Soup",
    description:
      "A nutritious soup from the Efik/Ibibio people, made with afang (okazi) leaves and waterleaf for a unique earthy flavor.",
    ingredients: [
      "500g waterleaf",
      "200g afang (okazi) leaves",
      "1/2 cup palm oil",
      "500g goat meat",
      "200g stockfish",
      "2 tbsp crayfish",
      "2 scotch bonnet peppers",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Cook meat and stockfish with seasoning.",
      "Blend waterleaf, pound afang leaves.",
      "Add palm oil, pepper, and crayfish to pot.",
      "Add leaves and simmer until done.",
    ],
    prepTimeMinutes: 25,
    cookTimeMinutes: 50,
    servings: 6,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 380,
    tags: ["vegetable", "swallow", "traditional"],
    image: "public/uploads/afang-soup.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Edikang Ikong Soup",
    description:
      "A premium vegetable soup loaded with pumpkin leaves, waterleaf, and meats, considered a “royal” delicacy.",
    ingredients: [
      "500g pumpkin leaves",
      "200g waterleaf",
      "1/2 cup palm oil",
      "500g goat meat",
      "200g stockfish",
      "2 tbsp crayfish",
      "2 scotch bonnet peppers",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Boil meat and stockfish with seasoning.",
      "Add palm oil, crayfish, and pepper.",
      "Stir in waterleaf and cook briefly.",
      "Add pumpkin leaves and simmer 5 minutes.",
    ],
    prepTimeMinutes: 25,
    cookTimeMinutes: 40,
    servings: 5,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 360,
    tags: ["vegetable", "traditional", "swallow"],
    image: "public/uploads/edikang.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Beans Porridge",
    description:
      "A soft and savory porridge made with brown beans, palm oil, and spices, filling and protein-rich.",
    ingredients: [
      "3 cups brown beans",
      "1/4 cup palm oil",
      "1 onion",
      "2 scotch bonnet peppers",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Cook beans until tender.",
      "Blend onion and pepper.",
      "Add palm oil, pepper mix, and seasoning.",
      "Simmer until thick.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 60,
    servings: 5,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 300,
    tags: ["beans", "protein", "comfort food"],
    image: "public/uploads/beans.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Tuwo Shinkafa",
    description:
      "A northern Nigerian staple made by mashing soft rice into swallow form, served with soups like Miyan Kuka.",
    ingredients: ["3 cups short-grain rice", "Water"],
    instructions: [
      "Cook rice with excess water until very soft.",
      "Mash rice into a smooth, stretchy consistency.",
      "Mould into balls and serve with soup.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 280,
    tags: ["swallow", "northern", "traditional"],
    image: "public/uploads/tuwo.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Oha Soup",
    description:
      "A rich eastern soup made with tender oha leaves, thickened with cocoyam paste, and flavored with palm oil.",
    ingredients: [
      "500g assorted meats",
      "200g oha leaves",
      "1/2 cup palm oil",
      "200g cocoyam paste",
      "2 tbsp crayfish",
      "2 scotch bonnet peppers",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Cook meats with seasoning.",
      "Add cocoyam paste to thicken.",
      "Stir in palm oil, crayfish, and pepper.",
      "Add oha leaves and simmer for 5 minutes.",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 50,
    servings: 5,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 400,
    tags: ["soup", "swallow", "traditional"],
    image: "public/uploads/oha.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Banga Soup",
    description:
      "A Delta delicacy prepared with palm nut extract, local spices, and meats, deeply aromatic and satisfying.",
    ingredients: [
      "1kg palm nuts or canned palm nut extract",
      "500g beef",
      "200g dried fish",
      "2 tbsp crayfish",
      "Banga spices",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Extract palm nut juice and boil.",
      "Add meat, fish, and seasoning.",
      "Add Banga spices and simmer.",
      "Cook until soup thickens.",
    ],
    prepTimeMinutes: 30,
    cookTimeMinutes: 60,
    servings: 6,
    difficulty: "Medium",
    cuisine: "Nigerian",
    caloriesPerServing: 420,
    tags: ["soup", "palm nut", "swallow"],
    image: "public/uploads/banga.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Yam Porridge (Asaro)",
    description:
      "Creamy yam stew cooked in palm oil and peppers, with soft yam chunks partially mashed for texture.",
    ingredients: [
      "6 Medium yams",
      "1/4 cup palm oil",
      "2 scotch bonnet peppers",
      "1 onion",
      "2 tbsp crayfish",
      "Spinach leaves",
      "Salt and seasoning cubes",
    ],
    instructions: [
      "Peel and cut yam into cubes.",
      "Boil yam with water, pepper, and onion.",
      "Add palm oil, crayfish, and seasoning.",
      "Mash partially and add spinach before serving.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    servings: 5,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 350,
    tags: ["yam", "comfort food", "porridge"],
    image: "public/uploads/yam.jpeg",
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Fried Plantain (Dodo)",
    description:
      "Sweet ripe plantains fried to golden perfection, served as a side dish or snack with rice, beans, or eggs.",
    ingredients: ["6 ripe plantains", "Vegetable oil", "Salt"],
    instructions: [
      "Peel and slice plantains diagonally.",
      "Sprinkle lightly with salt.",
      "Fry in hot oil until golden brown.",
      "Drain and serve.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Nigerian",
    caloriesPerServing: 250,
    tags: ["plantain", "side dish", "popular"],
    image: "public/uploads/platain.jpeg",
    mealType: ["lunch", "dinner", "snack"],
  },
];

async function products() {
  const cuisine = await prisma.cuisine.create({
    data: {
      slug: "nigerian",
      name: "Nigerian",
    },
  });

  for (let p of recipes) {
    const pro = await prisma.product.findFirst({
      where: { name: p.name },
    });

    if (pro) {
      console.warn(`⚠️ Skipping product ${p.name}, already exist`);
      continue;
    }
    const pr = await prisma.product.create({
      data: {
        name: p.name,
        slug: p.name.toLowerCase().replaceAll(" ", "-"), // Jollof rice -- jolof-rice
        description: p.description,
        ingredients: p.ingredients,
        instructions: p.instructions,
        mealType: p.mealType,
        prepTimeMinutes: p.prepTimeMinutes,
        cookTimeMinutes: p.cookTimeMinutes,
        tags: p.tags,
        servings: p.servings,
        caloriesPerServing: p.caloriesPerServing,
        difficulty: p.difficulty as "Hard" | "Medium" | "Easy",
        cuisine: {
          connect: {
            id: cuisine.id,
          },
        },
      },
    });

    const filePat = path.join(process.cwd(), p.image);
    const fileData = fs.readFileSync(filePat);
    const { url, thumbnailUrl, fileId, filePath } = await imagekit.upload({
      file: fileData,
      fileName: p.name,
      folder: "recipies",
    });
    await prisma.image.create({
      data: {
        url,
        thumbnailUrl,
        fileId,
        filePath,
        product: {
          connect: {
            id: pr.id,
          },
        },
      },
    });
  }
}

try {
  await prisma.$connect();
  await products();
} catch (error) {
  await prisma.$disconnect();
  console.log(error);
}
